GreenTourStorage/Controllers/RentController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GreenTourStorage.Models;
using GreenTourStorage.Queries;
using GreenTourStorage.Repository;
using GreenTourStorage.Services;
using Microsoft.AspNetCore.Authorization;

namespace GreenTourStorage.Controllers
{
    [Authorize]
    public class RentController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IStorekeeper _storekeeper;
        private readonly IRentQueries _rentQueries;

        private class ArticleCompare : IComparer<Article>
        {
            public int Compare(Article x, Article y)
                => x.CompareTo(y);
        }

        public RentController(IStorekeeper storekeeper, IArticleService articleService, IRentQueries rentQueries)
        {
            _storekeeper = storekeeper;
            _articleService = articleService;
            _rentQueries = rentQueries;
        }

        [HttpGet]
        [Route("Rent/{id:int}")]
        public async Task<IActionResult> Rent(int id)
        {
            return View(await _rentQueries.GetRent(id));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _rentQueries.GetRents());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var compare = new ArticleCompare();
            var particularArticles = _articleService.GetParticularOnStorage();
            particularArticles.Sort(compare);
            var multipleArticles = _articleService.GetMultipleOnStorage();
            multipleArticles.Sort(compare);

            var createRentDto = new CreateRentDto
            {
                Items = particularArticles.Select(q =>
                    new CreateRentItemDto
                    {
                        ArticleId = q.RegNum,
                        Type = q.Type,
                        Category = q.Category,
                        ActualCount =  1,
                        Description = q.Description,
                        Name = q.Name,
                        Price = q.Price.ToString(CultureInfo.InvariantCulture),
                        RequestedCount = 0,
                    }) .Concat(
                        multipleArticles.Select(q=>
                            new CreateRentItemDto
                            {
                                ArticleId = q.RegNum,
                                Type = q.Type,
                                Category = q.Category,
                                ActualCount = q.NowCount,
                                Description = q.Description,
                                Name = q.Name,
                                Price = q.Price.ToString(CultureInfo.InvariantCulture),
                                RequestedCount = 0,
                            }
                    ))
                    .ToArray()
            };
            return View(createRentDto);
        }




        [HttpPost]
        public async Task<IActionResult> Create (CreateRentDto dto)
        {
            var rent = await _storekeeper.CreateRent(dto);
            return RedirectToAction(rent.RentId.ToString());
        }

        [HttpPost]
        [Route("Rent/{id:int}_Finish")]
        [Route("Rent/{id:int}/Finish")]
        public IActionResult Finish (FinishRentDto dto)
        {
            _storekeeper.FinishRent(dto).Wait();
            return RedirectToAction(dto.RentId.ToString());
        }
    }

    public class CreateRentItemDto
    {
        public int ArticleId { get; set; }
        public ArticleType Type { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ActualCount { get; set; }
        public int RequestedCount { get; set; }
        public string Price { get; set; }
        public bool Joined { get; set; }
    }

    public class CreateRentDto
    {
        public CreateRentItemDto[] Items { get; set; }
        public string User { get; set; }
    }


    public class FinishRentItemDto
    {
        public int ArticleId { get; set; }

        public int ToRepair { get; set; }
        public int Returned { get; set; }
        public string Comment { get; set; }

    }

    public class FinishRentDto
    {
        public int RentId { get; set; }
        public FinishRentItemDto[] Items { get; set; }
    }
}

GreenTourStorage/Controllers/StorageController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using GreenTourStorage.Services;
using GreenTourStorage.Models;
using GreenTourStorage.Queries;
using Microsoft.AspNetCore.Authorization;

namespace GreenTourStorage.Controllers
{
    [Authorize]
    public class StorageController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IStorekeeper _storekeeper;
        private readonly IArticleQueries _articleQueries;

        private class CategoriesCompare : IComparer<Category>
        {
            public int Compare(Category x, Category y)
            {
                return x?.Name switch
                {
                    null when y?.Name == null => 0,
                    null => -1,
                    _ => y?.Name == null ? 1 : string.Compare(x.Name, y.Name, StringComparison.Ordinal)
                };
            }
        }

        private class ArticleCompare : IComparer<Article>
        {
            public int Compare(Article x, Article y)
                => x.CompareTo(y);
        }

        public StorageController (IArticleService articleService, IStorekeeper storekeeper, IArticleQueries articleQueries)
        {
            _articleService = articleService;
            _storekeeper = storekeeper;
            _articleQueries = articleQueries;
        }

        public IActionResult Index()
        {
            var compare = new ArticleCompare();
            var particularArticles = _articleService.GetAllParticular();
            particularArticles.Sort(compare);
            var multipleArticles = _articleService.GetAllMultiple();
            multipleArticles.Sort(compare);
            return View((particularArticles, multipleArticles));
        }


        [HttpGet]
        public IActionResult AddArticle()
        {
          var categories =  _articleService.GetAllCategories();
            categories.Sort(new CategoriesCompare());
            return View(categories);
        }


        [HttpPost]
        public IActionResult AddArticle (string articleName, string category,
            double price, string type,
                                        double? weight, int? maCount,
                                        int? regNum = null,
                                        string description = null,
                                        string comment = null)
        {
            try
            {
                if (type == "particular")
                {
                    var resultReg = _articleService.RegisterParticularArticle
                        (articleName, category, price, description, weight, regNum, comment!=null, comment);
                    return RedirectToAction("ParticularArticle", new { reg = resultReg });
                }

                if (type == "multiple")
                {
                    var resultReg = _articleService.RegisterMultipleArticle
                        (articleName, category, price, maCount.Value, description, weight);
                    return RedirectToAction("MultipleArticle", new { reg = resultReg });
                }

            }
            catch (Exception e)
            {
            //    throw new NotImplementedException();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult AddCategories()
        {
            var categories = _articleService.GetAllCategories();
            categories.Sort(new CategoriesCompare());
            return View(categories);
        }


        [HttpPost]
        public IActionResult AddCategories(string category)
        {
            try
            {
                _articleService.CreateCategory(category);
            }
            catch (Exception e) // TODO!!
            {
                throw new NotImplementedException();
            }
            return RedirectToAction("AddCategories");
        }

        [Route("Storage/ParticularArticle/{reg:int}")]
        [HttpGet]
        public IActionResult ParticularArticle(int reg)
        {
            return View((_articleService.GetParticularArticle(reg),
                _storekeeper.GetArticleRentStory(reg), _articleService.GetAllCategories()));
        }

        [Route("Storage/ParticularArticle/{reg:int}")]
        [HttpPost]
        public IActionResult ParticularArticle(int reg, string articleName,
                                                decimal? weight, double price, string category,
                                        string description = null, string comment = null)
        {
            _articleService.EditArticle(reg, articleName, price, description, category);
            var bm = comment != null;
            _articleService.SetBlackMarkParticularArticle(reg, bm, comment);
            if (weight.HasValue)
                _articleService.SetWeightParticularArticle(reg, weight.Value);
            return RedirectToAction("ParticularArticle", new { reg = reg });
        }

        [Route("Storage/MultipleArticle/{reg:int}")]
        [HttpGet]
        public async Task<IActionResult> MultipleArticle(int reg)
        {
            var ma = await _articleQueries.GetArticle(reg);
            return View(( ma,  _articleService.GetAllCategories()));
        }

        [Route("Storage/MultipleArticle/{reg:int}")]
        [HttpPost]
        public IActionResult MultipleArticle(int reg, string articleName,
                                            decimal? weight, double price, string category,
                                            int? maAdditionalCount,
                                            string description = null)
        {
            _articleService.EditArticle(reg, articleName, price, description, category);
            if ((maAdditionalCount.HasValue) && (maAdditionalCount.Value > 0))
                _articleService.RegisterAdditiveMultipleArticle(reg, maAdditionalCount.Value);
            if (weight.HasValue)
                _articleService.SetWeightMultipleArticle(reg, weight.Value);
            return RedirectToAction("MultipleArticle", new { reg = reg });
        }
    }
}

GreenTourStorage/Controllers/TenantController.cs
using System.Linq;
using GreenTourStorage.Dtos;
using Microsoft.AspNetCore.Mvc;
using GreenTourStorage.Services;
using Microsoft.AspNetCore.Authorization;

namespace GreenTourStorage.Controllers
{
    [Authorize]
    public class TenantController: Controller
    {
        private static IPaymaster _paymaster;

        public TenantController(IPaymaster paymaster)
        {
            _paymaster = paymaster;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_paymaster.GetAllTenants().ToList());
        }

        [HttpPost]
        public IActionResult Index(string phone)
        {
          //  _paymaster.AddClubman(phone);
            return RedirectToAction("Index");
        }

        [HttpGet("Tenant/Add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("Tenant/Add")]
        public IActionResult Add(TenantCreateDto createDto)
        {
            var tenant = _paymaster.AddTenant(createDto);
            return RedirectToAction("Index");
        }

        [Route("Tenant/{reg:int}")]
        [HttpGet]
        public IActionResult Tenant(int reg)
        {
            var tenant = _paymaster.GetTenant(reg);
            return View(tenant);
        }



    }
}

GreenTourStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <base href="/" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - Green Tour</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

   <link rel="stylesheet" href="~/css/site.css" />
     <link rel="stylesheet" href="~/css/storage_styles.css" />
      <script asp-src-include="~/js/simple/*.js"></script>
</head>
<body>

<nav class="navbar navbar-light navbar-expand-md fixed-top" style="background-color: darkgreen;">
    <a class="Logo" href="#">Green Tour</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">

        @if (@User.Identity.IsAuthenticated)
        {
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Склад
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-area="" asp-controller="Storage" asp-action="Index">Снаряжение</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Storage" asp-action="AddArticle">Добавить снаряжение</a>
                        <a  class="dropdown-item" asp-area="" asp-controller="Storage" asp-action="AddCategories">Категории</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Аренда
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-area="" asp-controller="Rent" asp-action="Index">История</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Rent" asp-action="Create">Выдать снаряжение</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Tenant" asp-action="Index">Участники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  asp-controller="Home" asp-action="Info">Информация</a>
                </li>
            </ul>
            <a class="nav-link ms-sm-2" asp-controller="Account" asp-action="Logout">Выйти</a>
        }
    </div>
</nav>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Green Tour Storage</p>
        </footer>
    </div>
</body>
</html>